steps:
# Get the secret password for the database
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args: ['-c', 'gcloud secrets versions access latest --secret=DATABASE_PASSWORD >> var.tmp ']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/timeoff-272103/timeoff:latest', '.' ]
  dir: './'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/timeoff-272103/timeoff:latest']

# Install npm dependencies
- id: 'node-install'
  name: 'gcr.io/cloud-builders/npm'
  args: ['install', 'sequelize', 'sequelize-cli', 'mysql']

# Deploy container image to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--image-url', 'gcr.io/timeoff-272103/timeoff:latest']

# Deploy updates to URL dispatches as needed
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'dispatch.yaml']

timeout: "600s"
images:
- 'gcr.io/timeoff-272103/timeoff:latest'

